### PR TITLE
fix: trim whitespaces from env name

### LINKED ISSUE #13: Handle NODE_ENV under npm on Windows
I noticed during development, `custom-env` was always falling back to the default `.env` file. It seems as though there's some edge cases when using under Windows.

When setting `NODE_ENV` and running through npm, it appears that `NODE_ENV` can get a whitespace character appended under certain conditions. This was causing `custom-env` to fail finding the file because https://github.com/erisanolasheni/custom-env/blob/master/lib/main.js#L85 was failing.

This can be replicated with the following:

**package.json**
```json
"scripts": {
  "start": "set NODE_ENV=development && node"
}
```

**Terminal**
```sh
$ npm start
> console.log(`|${process.env.NODE_ENV}|`)
|development |
```

### PR DESCRIPTION
**Pull request by coogie**
closes #13

### CODE REVIEW

**Comment by dhrma89** [comment]
When will this issue be fixed.

**Comment by coogie** [comment]
@erisanolasheni

**Comment by erisanolasheni** [comment]
We are sorry for this delay @coogie

**Comment by coogie** [comment]
No need to apologise. Hope you're staying safe! :)

**Pull request merged**
